export default {
    "High Performance AC Service": require("../images/serv/AC/High.jpg"),
    "Cooling Coil Change": require("../images/serv/AC/Cooling.jpg"),
    "Condenser Change": require("../images/serv/AC/Condenser.jpg"),
    "Compressor Change": require("../images/serv/AC/Compressor.jpg"),
    "V-Belt Change": require("../images/serv/AC/V_Belt.jpg"),
    "Radiator Change": require("../images/serv/AC/Radiator.jpg"),
    "Radiator Flush & Clean": require("../images/serv/AC/Radiator_Flush.jpg"),
    "Amaron(55 Months Warranty)": require("../images/serv/Battery/Amaron.jpg"),
    "Exide(55 Months Warranty)": require("../images/serv/Battery/Exide.jpg"),
    "Livguard(60 Months Warranty)": require("../images/serv/Battery/Livguard.png"),
    "Inspection/Diagnostics": require("../images/serv/Check-up/Inspection.jpg"),
    "Waterlog Assistance": require("../images/serv/Check-up/Waterlog.jpg"),
    "Engine Issues": require("../images/serv/Check-up/Engine.jpg"),
    "Rat Resistant Treatment": require("../images/serv/Cleaning/Rat_Resistant.jpg"),
    "Deep Cleaning Exterior & Interior Package": require("../images/serv/Cleaning/Deep_Cleaning.jpg"),
    "Interior Cleaning Package": require("../images/serv/Cleaning/Interior.jpg"),
    "Standard Package": require("../images/serv/Cleaning/Sanitation.jpg"),
    "Ceramic Coating & Treatment": require("../images/serv/Cleaning/Ceramic.jpg"),
    "Front Headlight": require("../images/serv/Electrical/Front.jpg"),
    "Rear Taillight": require("../images/serv/Electrical/Rear.jpg"),
    "Fog Light": require("../images/serv/Electrical/Fog.jpg"),
    "Accidental Inspection": require("../images/serv/Insurance/Accidental.jpg"),
    "Windshield Change": require("../images/serv/Insurance/Windshield.jpg"),
    "Towing": require("../images/serv/Insurance/Towing.jpg"),
    "Tyre Change": require("../images/serv/Insurance/Tyre.jpg"),
    "Insurance Claim": require("../images/serv/Insurance/Insurance.jpg"),
    "Complete Engine Scanning": require("../images/serv/Mechanical/Engine.png"),
    "Complete Suspension Check-up": require("../images/serv/Mechanical/Suspension.png"),
    "Clutch Set Change": require("../images/serv/Mechanical/Clutch.png"),
    "Fluids Inspection": require("../images/serv/Mechanical/Fluids.png"),
    "Engine Mounting Replacement": require("../images/serv/Mechanical/Mounting.png"),
    "Front Shock Absorber Replacement": require("../images/serv/Mechanical/Front.png"),
    "Rear Shock Absorber Replacement": require("../images/serv/Mechanical/Rear.png"),
    "Bonnet Paint Job": require("../images/serv/Paint/Bonnet.jpg"),
    "Front Bumper Paint Job": require("../images/serv/Paint/Front_Bumper.jpg"),
    "Rear Bumper Paint Job": require("../images/serv/Paint/Rear_Bumper.jpg"),
    "Left Fender Paint Job": require("../images/serv/Paint/Left_Fender.jpg"),
    "Right Fender Paint Job": require("../images/serv/Paint/Right_Fender.jpg"),
    "Left Front Door Paint": require("../images/serv/Paint/Left_Door.jpg"),
    "Left Rear Door Paint": require("../images/serv/Paint/Left_Door.jpg"),
    "Right Rear Door Paint": require("../images/serv/Paint/Right_Door.jpg"),
    "Right Front Door Paint": require("../images/serv/Paint/Right_Door.jpg"),
    "Boot Paint Job": require("../images/serv/Paint/Boot_Paint.jpg"),
    "Alloy Paint Job": require("../images/serv/Paint/Alloy.jpg"),
    "Full Body Dent Paint": require("../images/serv/Paint/Full_Body.jpg"),
    "Complete Wheel Care": require("../images/serv/Wheel/Complete.jpg"),
    "Door Glass Change" : require("../images/serv/Windshield/door.jpg"),
    "Front Windshield Change": require("../images/serv/Windshield/front.jpg"),
    "Rear Windshield Change": require("../images/serv/Windshield/rear.jpg"),
    "Standard Service": require("../images/serv/sp.jpg"),
    "Prime Service": require("../images/serv/pp.jpg"),
}